/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dwi_d
 */

import de.re.easymodbus.exceptions.ModbusException;
import de.re.easymodbus.modbusclient.ModbusClient;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;
import java.util.Date;


public class HMISmartHome extends javax.swing.JFrame {

    /**
     * Creates new form HMISmartHome
     */
    public HMISmartHome() {
        initComponents();
        ActionListener taskPerformer = (ActionEvent evt) -> {
            double QW128;
            double QW130;
            
            
            ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
            try
            {
                modbusClient.Connect();
                QW128 = modbusClient.ReadHoldingRegisters(65, 1)[0];
                QW128 = QW128 / 10;
                TfSuhu.setText(Double.toString(QW128));
                modbusClient.Disconnect();
                bacaDI();
                
            }
            catch (ModbusException | IOException e)
            {
            }
        };          
    new Timer(1000, taskPerformer).start();
    
    }

    
public void bacaDI(){
    boolean i00;
    String i00s;
    boolean i01;
    String i01s;
    boolean i02;
    ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
		try
		{
			modbusClient.Connect();  
                        //---TfSensorGerbang
                        i00 = modbusClient.ReadDiscreteInputs(0,1)[0];                      
                        i00s = Boolean.toString(i00); 
                        if("true".equals(i00s)){
                        TfSensorGerbang.setText("Pintu Gerbang Terbuka");
                        TfSensorGerbang.setBackground(Color.RED);
                        }
                        else if("false".equals(i00s)){
                        TfSensorGerbang.setText("Pintu Gerbang Tertutup");
                        TfSensorGerbang.setBackground(Color.GREEN);
                        }
                        //---TfSensorPintuDepan
                        i01 = modbusClient.ReadDiscreteInputs(1,1)[0];                      
                        i01s = Boolean.toString(i01); 
                        if("true".equals(i01s)){
                        TfSensorPintuDepan.setText("Pintu Depan Terbuka");
                        TfSensorPintuDepan.setBackground(Color.RED);
                        }
                        else if("false".equals(i01s)){
                        TfSensorPintuDepan.setText("Pintu Depan Tertutup");
                        TfSensorPintuDepan.setBackground(Color.GREEN);
                        }
                }      
		catch (ModbusException | IOException e)
		{		
		}
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbJudul = new javax.swing.JLabel();
        Bt2OFF = new javax.swing.JButton();
        Bt2ON = new javax.swing.JButton();
        TfSensorGerbang = new javax.swing.JTextField();
        TfSensorPintuDepan = new javax.swing.JTextField();
        TfSuhu = new javax.swing.JTextField();
        LbUnitSuhu = new javax.swing.JLabel();
        Bt1ON = new javax.swing.JButton();
        Bt1OFF = new javax.swing.JButton();
        TfLampu1 = new javax.swing.JTextField();
        TfLampu2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LbJudul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LbJudul.setText("Smart Home");

        Bt2OFF.setText(" OFF");
        Bt2OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt2OFFActionPerformed(evt);
            }
        });

        Bt2ON.setText("ON");
        Bt2ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt2ONActionPerformed(evt);
            }
        });

        TfSensorGerbang.setBackground(new java.awt.Color(255, 0, 0));
        TfSensorGerbang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TfSensorGerbang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfSensorGerbang.setText(" PINTU GERBANG TERBUKA");

        TfSensorPintuDepan.setBackground(new java.awt.Color(102, 255, 51));
        TfSensorPintuDepan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TfSensorPintuDepan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfSensorPintuDepan.setText(" PINTU DEPAN TERTUTUP");

        TfSuhu.setBackground(new java.awt.Color(204, 255, 204));
        TfSuhu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TfSuhu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfSuhu.setText("23.5");
        TfSuhu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbUnitSuhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LbUnitSuhu.setText("°C");

        Bt1ON.setText(" ON");
        Bt1ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt1ONActionPerformed(evt);
            }
        });

        Bt1OFF.setText(" OFF");
        Bt1OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt1OFFActionPerformed(evt);
            }
        });

        TfLampu1.setBackground(new java.awt.Color(102, 102, 102));
        TfLampu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TfLampu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfLampu1.setText("LAMPU 1 OFF");

        TfLampu2.setBackground(new java.awt.Color(102, 102, 102));
        TfLampu2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TfLampu2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfLampu2.setText("LAMPU 2 OFF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(LbJudul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bt1ON, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bt1OFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TfLampu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TfLampu2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Bt2ON, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Bt2OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TfSensorGerbang, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(TfSensorPintuDepan))
                        .addGap(0, 41, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TfSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbUnitSuhu)
                .addGap(95, 95, 95))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bt1OFF, Bt1ON});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LbJudul)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(LbUnitSuhu)))
                        .addGap(39, 39, 39)
                        .addComponent(TfSensorGerbang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TfSensorPintuDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 130, Short.MAX_VALUE)
                        .addComponent(TfLampu1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt1OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt1ON))
                        .addGap(18, 18, 18)
                        .addComponent(TfLampu2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt2ON)
                            .addComponent(Bt2OFF, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(138, 138, 138))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bt1ON, Bt2OFF, Bt2ON});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TfLampu1, TfLampu2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TfSensorGerbang, TfSensorPintuDepan});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt1ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt1ONActionPerformed
        // TODO add your handling code here:
        TfLampu1.setBackground(Color.red);
        TfLampu1.setText("LAMPU 1 ON");
        ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
		try
		{
			modbusClient.Connect();                     
                        modbusClient.WriteSingleCoil(0,true);                         
                        modbusClient.Disconnect();
		}
		catch (Exception e)
		{		
		}
    }//GEN-LAST:event_Bt1ONActionPerformed

    private void Bt1OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt1OFFActionPerformed
        // TODO add your handling code here:
        TfLampu1.setBackground(Color.gray);
        TfLampu1.setText("LAMPU 1 OFF");
        ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
		try
		{
			modbusClient.Connect();                     
                        modbusClient.WriteSingleCoil(0,false);                         
                        modbusClient.Disconnect();
		}
		catch (Exception e)
		{		
		}
    }//GEN-LAST:event_Bt1OFFActionPerformed

    private void Bt2ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2ONActionPerformed
        TfLampu2.setBackground(Color.red);
        TfLampu2.setText("LAMPU 2 ON");
        ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
		try
		{
			modbusClient.Connect();                     
                        modbusClient.WriteSingleCoil(1,true);                         
                        modbusClient.Disconnect();
		}
		catch (Exception e)
		{		
		}
    }//GEN-LAST:event_Bt2ONActionPerformed

    private void Bt2OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2OFFActionPerformed
        // TODO add your handling code here:
        TfLampu2.setBackground(Color.gray);
        TfLampu2.setText("LAMPU 2 OFF");
        ModbusClient modbusClient = new ModbusClient("127.0.0.1",502);
		try
		{
			modbusClient.Connect();                     
                        modbusClient.WriteSingleCoil(1,false);                         
                        modbusClient.Disconnect();
		}
		catch (Exception e)
		{		
		}
    }//GEN-LAST:event_Bt2OFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMISmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMISmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMISmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMISmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMISmartHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt1OFF;
    private javax.swing.JButton Bt1ON;
    private javax.swing.JButton Bt2OFF;
    private javax.swing.JButton Bt2ON;
    private javax.swing.JLabel LbJudul;
    private javax.swing.JLabel LbUnitSuhu;
    private javax.swing.JTextField TfLampu1;
    private javax.swing.JTextField TfLampu2;
    private javax.swing.JTextField TfSensorGerbang;
    private javax.swing.JTextField TfSensorPintuDepan;
    private javax.swing.JTextField TfSuhu;
    // End of variables declaration//GEN-END:variables
}
